env:
  global:
  - REPO_DIR=checkout
  - BUILD_DEPENDS="-Ur checkout/requirements.txt"
  - TEST_DEPENDS="-Ur checkout/requirements.txt"
  - PLAT=x86_64
  - UNICODE_WIDTH=32
  - WHEELHOUSE_UPLOADER_USERNAME=travis-worker
  - HOMEBREW_NO_AUTO_UPDATE=1
  - secure: nc7wgtPyTclTDwYIqWmJyS1Xc9Tk/IXc0FIz6YEkCRbx3V5HshDkbs43wYmF6YVjrcOIgq2EH8NxMmSnH+7qipgptaWtHWguLE2B88xNDAzuZ4mTAzYVG5vVBcpXeh73e+YEzory0+4MXynjI/agEsgzFqNGFnkOAEqNtz9dJfyX739NjoMEwCRyr6k6XJV7IH9vAz/21Er7oe4HlYetncid9AnSTtZXzL11sRioCm4d/igJ8QP6MPUgBNKJ9u9jjFsAhifgti6w7IDiUMkz0xLD2AdmHniXopcdfxQyNBRYZ5Kt1nONDJtQQhLN59llnExR2n5OGgRJj7HNoZlaBS37ZkhhXUKmN3Jz1tGITCPozqDjT+G7o0gMmWl0FLcBmanUKbGS9wofzL8hXgg6JeH8/SQeAyDOfrcOTpXHQfOcvY1c9uSjdPZTBMwolZg0x1xhfrOyYzDKiMmc6ePRwx6I8cMhDYIYyudEbMUjdKWxTZ8W7qILMxEO9W0+zsQS7tddtp1XHfvpdmtTN/9S/qCxf7qdsecFOv1eqZ9bjMVOOVDe7odtyA2z+qHy1ilnkXgkMSOBB0u0Sc7dOxVCcZ1NUdQtoMlcvhCwKmzQCmxNVNtvQ2GP16hB4ljAQimzKzmKeaza6y0cJJvpvCXsdwkjGddDJVY0Dy9jQpHDKeE=
language: python
sudo: required
dist: xenial
services: docker
cache: false
if: type = push AND tag IS blank AND branch =~ /^branch-for-/
matrix:
  include:
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.6
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.7
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.8
  - os: osx
    language: generic
    env:
    - MB_PYTHON_VERSION=3.6
  - os: osx
    language: generic
    env:
    - MB_PYTHON_VERSION=3.7
  - os: osx
    language: generic
    env:
    - MB_PYTHON_VERSION=3.8
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gettext; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --force gettext; fi
- pip install -Ur ./requirements.txt
- eval $(python ./run.py build-spec build-spec.json)
- git clone "${BUILD_SPEC_CLONE_URL}" "$REPO_DIR"
- export BUILD_COMMIT="${BUILD_SPEC_COMMIT}"
- export PACKAGE_NAME="${BUILD_SPEC_PACKAGE_NAME}"
- cat config.sh.template | envsubst > config.sh
- source multibuild/common_utils.sh
- source multibuild/travis_steps.sh
- export -u MACOSX_DEPLOYMENT_TARGET=10.15
- before_install
install:
- clean_code $REPO_DIR $BUILD_COMMIT
- build_wheel $REPO_DIR $PLAT
script:
- install_run $PLAT
after_success:
- pip install -Ur ./requirements.txt
- python ./run.py upload --build-spec build-spec.json ${TRAVIS_BUILD_DIR}/wheelhouse
