environment:
  global:
    GITHUB_SECRET_TOKEN:
      secure: "sfzuXpOt66zPmBqujsi/tkoJOelQeJgV98lCS3WZXi8Zsisj+sGdAfXz+SZjqur6"

  matrix:
    - PYTHON: C:\Python37-x64
      PYTHON_VERSION: 3.7
      PYTHON_ARCH: 64

    - PYTHON: C:\Python36-x64
      PYTHON_VERSION: 3.6
      PYTHON_ARCH: 64


# Don't generate builds for tags, PRs, or the master branch
skip_tags: true
branches:
  only:
    - /^branch-for-/

install:
    - echo "Filesystem root:"
    - dir C:\
    - echo "Installed SDKs:"
    - dir "C:/Program Files/Microsoft SDKs/Windows"
    # Fetch submodules
    - git submodule update --init --recursive
    # Install new Python if necessary
    - ps: .\multibuild\install_python.ps1
    # Set up path
    - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

    # Check that we have the expected version and architecture for Python
    - "echo We want: Python %PYTHON_VERSION%, %PYTHON_ARCH% bit"
    - "echo We're using: %PYTHON%"
    - "echo We got:"
    - python --version
    - python -c "import struct; print(struct.calcsize('P') * 8, 'bit')"

    # Get a modern working environment
    - python -m pip install -U pip setuptools wheel virtualenv

build_script:
    - pip install -Ur requirements.txt
    - python -u run.py appveyor-build --build-spec build-spec.json
